/* 회원 */
CREATE TABLE USERS (
	USER_ID VARCHAR2(200) NOT NULL, /* 이메일아이디 */
	USER_NICKNAME VARCHAR2(100) NOT NULL, /* 닉네임 */
	USER_PASSWORD VARCHAR2(100) NOT NULL, /* 비밀번호 */
	USER_NAME VARCHAR2(100), /* 이름 */
	USER_TEL VARCHAR2(100), /* 전화번호 */
	USER_BIRTH DATE, /* 생일 */
	USER_RATING NUMBER, /* 등급 */
	USER_THEME NUMBER, /* 테마 */
	USER_SIGN_DATE DATE NOT NULL, /* 가입일자 */
	USER_PIC BLOB /* 회원사진 */
);

COMMENT ON TABLE USERS IS '회원';

COMMENT ON COLUMN USERS.USER_ID IS '이메일아이디';

COMMENT ON COLUMN USERS.USER_NICKNAME IS '닉네임';

COMMENT ON COLUMN USERS.USER_PASSWORD IS '비밀번호';

COMMENT ON COLUMN USERS.USER_NAME IS '이름';

COMMENT ON COLUMN USERS.USER_TEL IS '전화번호';

COMMENT ON COLUMN USERS.USER_BIRTH IS '생일';

COMMENT ON COLUMN USERS.USER_RATING IS '등급';

COMMENT ON COLUMN USERS.USER_THEME IS '테마';

COMMENT ON COLUMN USERS.USER_SIGN_DATE IS '가입일자';

COMMENT ON COLUMN USERS.USER_PIC IS '회원사진';

CREATE UNIQUE INDEX PK_USERS
	ON USERS (
		USER_ID ASC
	);

ALTER TABLE USERS
	ADD
		CONSTRAINT PK_USERS
		PRIMARY KEY (
			USER_ID
		);

/* 팔로우 */
CREATE TABLE FOLLOW (
	FOLLOW_NO NUMBER NOT NULL, /* 팔로우번호 */
	FOLLOWER VARCHAR2(200) NOT NULL, /* 팔로워 */
	FOLLOWEE VARCHAR2(200) NOT NULL /* 팔로위 */
);

COMMENT ON TABLE FOLLOW IS '팔로우';

COMMENT ON COLUMN FOLLOW.FOLLOW_NO IS '팔로우번호';

COMMENT ON COLUMN FOLLOW.FOLLOWER IS '팔로워';

COMMENT ON COLUMN FOLLOW.FOLLOWEE IS '팔로위';

CREATE UNIQUE INDEX PK_FOLLOW
	ON FOLLOW (
		FOLLOW_NO ASC
	);

ALTER TABLE FOLLOW
	ADD
		CONSTRAINT PK_FOLLOW
		PRIMARY KEY (
			FOLLOW_NO
		);

/* 회원약관 */
CREATE TABLE STIPULATION (
	STIPUL_NO NUMBER NOT NULL, /* 약관번호 */
	STIPUL_TITLE VARCHAR2(100), /* 약관이름 */
	STIPUL_CONT VARCHAR2(2000), /* 약관내용 */
	STIPUL_ESSEN NUMBER, /* 필수여부 */
	STIPUL_SEQ NUMBER, /* 약관순서 */
	STIPUL_USE NUMBER /* 약관사용여부 */
);

COMMENT ON TABLE STIPULATION IS '회원약관';

COMMENT ON COLUMN STIPULATION.STIPUL_NO IS '약관번호';

COMMENT ON COLUMN STIPULATION.STIPUL_TITLE IS '약관이름';

COMMENT ON COLUMN STIPULATION.STIPUL_CONT IS '약관내용';

COMMENT ON COLUMN STIPULATION.STIPUL_ESSEN IS '필수여부';

COMMENT ON COLUMN STIPULATION.STIPUL_SEQ IS '약관순서';

COMMENT ON COLUMN STIPULATION.STIPUL_USE IS '약관사용여부';

/* 약관동의이력 */
CREATE TABLE STIPULRATION_HIS (
	STIPUL_NO NUMBER NOT NULL, /* 약관번호 */
	USER_ID VARCHAR2(200) NOT NULL, /* 이메일아이디 */
	STIPUL_AGREE NUMBER NOT NULL /* 동의여부 */
);

COMMENT ON TABLE STIPULRATION_HIS IS '약관동의이력';

COMMENT ON COLUMN STIPULRATION_HIS.STIPUL_NO IS '약관번호';

COMMENT ON COLUMN STIPULRATION_HIS.USER_ID IS '이메일아이디';

COMMENT ON COLUMN STIPULRATION_HIS.STIPUL_AGREE IS '동의여부';

CREATE UNIQUE INDEX PK_STIPULRATION_HIS
	ON STIPULRATION_HIS (
		STIPUL_NO ASC
	);

ALTER TABLE STIPULRATION_HIS
	ADD
		CONSTRAINT PK_STIPULRATION_HIS
		PRIMARY KEY (
			STIPUL_NO
		);

/* 학급 */
CREATE TABLE CLASS (
	CLASS_NAME VARCHAR2(500) NOT NULL, /* 학급이름 */
	USER_ID VARCHAR2(200) NOT NULL, /* 이메일아이디 */
	CLASS_START DATE NOT NULL, /* 학급시작일 */
	CLASS_END DATE NOT NULL /* 학급종료일 */
);

COMMENT ON TABLE CLASS IS '학급';

COMMENT ON COLUMN CLASS.CLASS_NAME IS '학급이름';

COMMENT ON COLUMN CLASS.USER_ID IS '이메일아이디';

COMMENT ON COLUMN CLASS.CLASS_START IS '학급시작일';

COMMENT ON COLUMN CLASS.CLASS_END IS '학급종료일';

CREATE UNIQUE INDEX PK_CLASS
	ON CLASS (
		CLASS_NAME ASC
	);

ALTER TABLE CLASS
	ADD
		CONSTRAINT PK_CLASS
		PRIMARY KEY (
			CLASS_NAME
		);

/* 피드 */
CREATE TABLE FEED (
	FEED_NO NUMBER NOT NULL, /* 피드번호 */
	USER_ID VARCHAR2(200) NOT NULL, /* 이메일아이디 */
	FEED_CONT VARCHAR2(2000) NOT NULL, /* 피드내용 */
	FEED_PIC BLOB, /* 피드사진 */
	FEED_DATE DATE NOT NULL /* 피드작성일 */
);

COMMENT ON TABLE FEED IS '피드';

COMMENT ON COLUMN FEED.FEED_NO IS '피드번호';

COMMENT ON COLUMN FEED.USER_ID IS '이메일아이디';

COMMENT ON COLUMN FEED.FEED_CONT IS '피드내용';

COMMENT ON COLUMN FEED.FEED_PIC IS '피드사진';

COMMENT ON COLUMN FEED.FEED_DATE IS '피드작성일';

CREATE UNIQUE INDEX PK_FEED
	ON FEED (
		FEED_NO ASC
	);

ALTER TABLE FEED
	ADD
		CONSTRAINT PK_FEED
		PRIMARY KEY (
			FEED_NO
		);

/* 알림 */
CREATE TABLE ALARM (
	ALARM_NO NUMBER NOT NULL, /* 알림번호 */
	USER_ID VARCHAR2(200) NOT NULL, /* 이메일아이디 */
	ALARM_CONT VARCHAR2(200) NOT NULL, /* 알림내용 */
	ALARM_TYPE NUMBER NOT NULL, /* 알림유형 */
	ALARM_DATE DATE NOT NULL, /* 알림시간 */
	ALARM_CHK NUMBER, /* 알림확인여부 */
	ALARM_CHK_DATE DATE /* 알림확인시간 */
);

COMMENT ON TABLE ALARM IS '알림';

COMMENT ON COLUMN ALARM.ALARM_NO IS '알림번호';

COMMENT ON COLUMN ALARM.USER_ID IS '이메일아이디';

COMMENT ON COLUMN ALARM.ALARM_CONT IS '알림내용';

COMMENT ON COLUMN ALARM.ALARM_TYPE IS '알림유형';

COMMENT ON COLUMN ALARM.ALARM_DATE IS '알림시간';

COMMENT ON COLUMN ALARM.ALARM_CHK IS '알림확인여부';

COMMENT ON COLUMN ALARM.ALARM_CHK_DATE IS '알림확인시간';

CREATE UNIQUE INDEX PK_ALARM
	ON ALARM (
		ALARM_NO ASC
	);

ALTER TABLE ALARM
	ADD
		CONSTRAINT PK_ALARM
		PRIMARY KEY (
			ALARM_NO
		);

/* 메시지 */
CREATE TABLE MESSAGE (
	MSG_NO NUMBER NOT NULL, /* 메시지번호 */
	MSG_TARGET_ID VARCHAR2(200) NOT NULL, /* 수신자 */
	MSG_SENDER VARCHAR2(200) NOT NULL, /* 발신자 */
	MSG_CONTENT VARCHAR2(2000) NOT NULL, /* 메시지내용 */
	MSG_SENDDATE DATE NOT NULL, /* 발송일자 */
	MSG_OPENDATE DATE NOT NULL /* 열람일자 */
);

COMMENT ON TABLE MESSAGE IS '메시지';

COMMENT ON COLUMN MESSAGE.MSG_NO IS '메시지번호';

COMMENT ON COLUMN MESSAGE.MSG_TARGET_ID IS '수신자';

COMMENT ON COLUMN MESSAGE.MSG_SENDER IS '발신자';

COMMENT ON COLUMN MESSAGE.MSG_CONTENT IS '메시지내용';

COMMENT ON COLUMN MESSAGE.MSG_SENDDATE IS '발송일자';

COMMENT ON COLUMN MESSAGE.MSG_OPENDATE IS '열람일자';

CREATE UNIQUE INDEX PK_MESSAGE
	ON MESSAGE (
		MSG_NO ASC
	);

ALTER TABLE MESSAGE
	ADD
		CONSTRAINT PK_MESSAGE
		PRIMARY KEY (
			MSG_NO
		);

/* 신고피드 */
CREATE TABLE BLAME (
	BLAME_NO NUMBER NOT NULL, /* 신고번호 */
	USER_ID VARCHAR2(200), /* 신고한 회원 */
	TARGET_ID VARCHAR2(200), /* 신고당한회원 */
	FEED_NO NUMBER, /* 피드번호 */
	TARGET_TYPE NUMBER, /* 신고종류 */
	BLAME_DATE DATE /* 신고일시 */
);

COMMENT ON TABLE BLAME IS '신고피드';

COMMENT ON COLUMN BLAME.BLAME_NO IS '신고번호';

COMMENT ON COLUMN BLAME.USER_ID IS '신고한 회원';

COMMENT ON COLUMN BLAME.TARGET_ID IS '신고당한회원';

COMMENT ON COLUMN BLAME.FEED_NO IS '피드번호';

COMMENT ON COLUMN BLAME.TARGET_TYPE IS '신고종류';

COMMENT ON COLUMN BLAME.BLAME_DATE IS '신고일시';

CREATE UNIQUE INDEX PK_BLAME
	ON BLAME (
		BLAME_NO ASC
	);

ALTER TABLE BLAME
	ADD
		CONSTRAINT PK_BLAME
		PRIMARY KEY (
			BLAME_NO
		);

/* 피드 댓글 */
CREATE TABLE FEED_COMMENT (
	FEED_COM_NO NUMBER NOT NULL, /* 피드댓글번호 */
	FEED_NO NUMBER NOT NULL, /* 피드번호 */
	USER_ID VARCHAR2(200) NOT NULL, /* 이메일아이디 */
	FEED_COM_CONT VARCHAR2(1000) NOT NULL, /* 피드댓글내용 */
	FEED_COM_DATE DATE NOT NULL /* 피드댓글시간 */
);

COMMENT ON TABLE FEED_COMMENT IS '피드 댓글';

COMMENT ON COLUMN FEED_COMMENT.FEED_COM_NO IS '피드댓글번호';

COMMENT ON COLUMN FEED_COMMENT.FEED_NO IS '피드번호';

COMMENT ON COLUMN FEED_COMMENT.USER_ID IS '이메일아이디';

COMMENT ON COLUMN FEED_COMMENT.FEED_COM_CONT IS '피드댓글내용';

COMMENT ON COLUMN FEED_COMMENT.FEED_COM_DATE IS '피드댓글시간';

CREATE UNIQUE INDEX PK_FEED_COMMENT
	ON FEED_COMMENT (
		FEED_COM_NO ASC
	);

ALTER TABLE FEED_COMMENT
	ADD
		CONSTRAINT PK_FEED_COMMENT
		PRIMARY KEY (
			FEED_COM_NO
		);

/* 스터디 */
CREATE TABLE STUDY (
	STUDY_NO NUMBER NOT NULL, /* 스터디번호 */
	STUDY_ADMIN VARCHAR2(200), /* 스터디관리자 */
	STUDY_NAME VARCHAR2(100), /* 스터디이름 */
	STUDY_DATE DATE NOT NULL, /* 개설일 */
	STUDY_MEM VARCHAR2(50) /* 스터디원 */
);

COMMENT ON TABLE STUDY IS '스터디';

COMMENT ON COLUMN STUDY.STUDY_NO IS '스터디번호';

COMMENT ON COLUMN STUDY.STUDY_ADMIN IS '스터디관리자';

COMMENT ON COLUMN STUDY.STUDY_NAME IS '스터디이름';

COMMENT ON COLUMN STUDY.STUDY_DATE IS '개설일';

COMMENT ON COLUMN STUDY.STUDY_MEM IS '스터디원';

CREATE UNIQUE INDEX PK_STUDY
	ON STUDY (
		STUDY_NO ASC
	);

ALTER TABLE STUDY
	ADD
		CONSTRAINT PK_STUDY
		PRIMARY KEY (
			STUDY_NO
		);

/* 이메일인증 */
CREATE TABLE EMAIL_CHECK (
	EMAIL_CHK_NO NUMBER NOT NULL, /* 이메일인증번호 */
	EMAIL_CHK_DATE DATE NOT NULL, /* 인증번호발송시간 */
	EMAIL_CHK_CONT VARCHAR2(200) NOT NULL, /* 인증번호내용 */
	EMAIL_CHK_ADDR VARCHAR2(200) NOT NULL /* 이메일주소 */
);

COMMENT ON TABLE EMAIL_CHECK IS '이메일인증';

COMMENT ON COLUMN EMAIL_CHECK.EMAIL_CHK_NO IS '이메일인증번호';

COMMENT ON COLUMN EMAIL_CHECK.EMAIL_CHK_DATE IS '인증번호발송시간';

COMMENT ON COLUMN EMAIL_CHECK.EMAIL_CHK_CONT IS '인증번호내용';

COMMENT ON COLUMN EMAIL_CHECK.EMAIL_CHK_ADDR IS '이메일주소';

CREATE UNIQUE INDEX PK_EMAIL_CHECK
	ON EMAIL_CHECK (
		EMAIL_CHK_NO ASC
	);

ALTER TABLE EMAIL_CHECK
	ADD
		CONSTRAINT PK_EMAIL_CHECK
		PRIMARY KEY (
			EMAIL_CHK_NO
		);

/* 공지사항 */
CREATE TABLE NOTICE (
	NOTICE_NO NUMBER NOT NULL, /* 공지사항번호 */
	USER_ID VARCHAR2(200) NOT NULL, /* 이메일아이디 */
	NOTICE_CONT VARCHAR2(2000) NOT NULL, /* 공지사항내용 */
	NOTICE_PIC BLOB, /* 공지사항사진 */
	NOTICE_DATE DATE NOT NULL /* 공지사항작성일 */
);

COMMENT ON TABLE NOTICE IS '공지사항';

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지사항번호';

COMMENT ON COLUMN NOTICE.USER_ID IS '이메일아이디';

COMMENT ON COLUMN NOTICE.NOTICE_CONT IS '공지사항내용';

COMMENT ON COLUMN NOTICE.NOTICE_PIC IS '공지사항사진';

COMMENT ON COLUMN NOTICE.NOTICE_DATE IS '공지사항작성일';

CREATE UNIQUE INDEX PK_NOTICE
	ON NOTICE (
		NOTICE_NO ASC
	);

ALTER TABLE NOTICE
	ADD
		CONSTRAINT PK_NOTICE
		PRIMARY KEY (
			NOTICE_NO
		);

/* 공지사항댓글 */
CREATE TABLE NOTICE_COMMENT (
	NOTICE_COM_NO NUMBER NOT NULL, /* 공지사항댓글번호 */
	NOTICE_NO NUMBER NOT NULL, /* 공지사항번호 */
	USER_ID VARCHAR2(200) NOT NULL, /* 이메일아이디 */
	NOTICE_COM_CONT VARCHAR2(1000) NOT NULL, /* 공지사항댓글내용 */
	NOTICE_COM_DATE DATE NOT NULL /* 공지사항댓글시간 */
);

COMMENT ON TABLE NOTICE_COMMENT IS '공지사항댓글';

COMMENT ON COLUMN NOTICE_COMMENT.NOTICE_COM_NO IS '공지사항댓글번호';

COMMENT ON COLUMN NOTICE_COMMENT.NOTICE_NO IS '공지사항번호';

COMMENT ON COLUMN NOTICE_COMMENT.USER_ID IS '이메일아이디';

COMMENT ON COLUMN NOTICE_COMMENT.NOTICE_COM_CONT IS '공지사항댓글내용';

COMMENT ON COLUMN NOTICE_COMMENT.NOTICE_COM_DATE IS '공지사항댓글시간';

CREATE UNIQUE INDEX PK_NOTICE_COMMENT
	ON NOTICE_COMMENT (
		NOTICE_COM_NO ASC
	);

ALTER TABLE NOTICE_COMMENT
	ADD
		CONSTRAINT PK_NOTICE_COMMENT
		PRIMARY KEY (
			NOTICE_COM_NO
		);

ALTER TABLE FOLLOW
	ADD
		CONSTRAINT FK_USERS_TO_FOLLOW
		FOREIGN KEY (
			FOLLOWER
		)
		REFERENCES USERS (
			USER_ID
		);

ALTER TABLE FOLLOW
	ADD
		CONSTRAINT FK_USERS_TO_FOLLOW2
		FOREIGN KEY (
			FOLLOWEE
		)
		REFERENCES USERS (
			USER_ID
		);

ALTER TABLE STIPULATION
	ADD
		CONSTRAINT FK_STIPULRATION_HIS_TO_STIPULATION
		FOREIGN KEY (
			STIPUL_NO
		)
		REFERENCES STIPULRATION_HIS (
			STIPUL_NO
		);

ALTER TABLE STIPULRATION_HIS
	ADD
		CONSTRAINT FK_USERS_TO_STIPULRATION_HIS
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USERS (
			USER_ID
		);

ALTER TABLE CLASS
	ADD
		CONSTRAINT FK_USERS_TO_CLASS
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USERS (
			USER_ID
		);

ALTER TABLE FEED
	ADD
		CONSTRAINT FK_USERS_TO_FEED
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USERS (
			USER_ID
		);

ALTER TABLE ALARM
	ADD
		CONSTRAINT FK_USERS_TO_ALARM
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USERS (
			USER_ID
		);

ALTER TABLE MESSAGE
	ADD
		CONSTRAINT FK_USERS_TO_MESSAGE
		FOREIGN KEY (
			MSG_TARGET_ID
		)
		REFERENCES USERS (
			USER_ID
		);

ALTER TABLE MESSAGE
	ADD
		CONSTRAINT FK_USERS_TO_MESSAGE2
		FOREIGN KEY (
			MSG_SENDER
		)
		REFERENCES USERS (
			USER_ID
		);

ALTER TABLE BLAME
	ADD
		CONSTRAINT FK_USERS_TO_BLAME
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USERS (
			USER_ID
		);

ALTER TABLE BLAME
	ADD
		CONSTRAINT FK_USERS_TO_BLAME2
		FOREIGN KEY (
			TARGET_ID
		)
		REFERENCES USERS (
			USER_ID
		);

ALTER TABLE BLAME
	ADD
		CONSTRAINT FK_FEED_TO_BLAME
		FOREIGN KEY (
			FEED_NO
		)
		REFERENCES FEED (
			FEED_NO
		);

ALTER TABLE FEED_COMMENT
	ADD
		CONSTRAINT FK_FEED_TO_FEED_COMMENT
		FOREIGN KEY (
			FEED_NO
		)
		REFERENCES FEED (
			FEED_NO
		);

ALTER TABLE FEED_COMMENT
	ADD
		CONSTRAINT FK_USERS_TO_FEED_COMMENT
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USERS (
			USER_ID
		);

ALTER TABLE STUDY
	ADD
		CONSTRAINT FK_USERS_TO_STUDY
		FOREIGN KEY (
			STUDY_ADMIN
		)
		REFERENCES USERS (
			USER_ID
		);

ALTER TABLE NOTICE
	ADD
		CONSTRAINT FK_USERS_TO_NOTICE
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USERS (
			USER_ID
		);

ALTER TABLE NOTICE_COMMENT
	ADD
		CONSTRAINT FK_USERS_TO_NOTICE_COMMENT
		FOREIGN KEY (
			USER_ID
		)
		REFERENCES USERS (
			USER_ID
		);

ALTER TABLE NOTICE_COMMENT
	ADD
		CONSTRAINT FK_NOTICE_TO_NOTICE_COMMENT
		FOREIGN KEY (
			NOTICE_NO
		)
		REFERENCES NOTICE (
			NOTICE_NO
		);
        
        
        
        --/////////////////////////////////////////////////////////////////-
        --TEST --
        
        /* 학급 */
CREATE TABLE CLASS (
	CLASS_NO NUMBER NOT NULL, /* 학급번호 */
	CLASS_START DATE NOT NULL, /* 학급시작일 */
	CLASS_END DATE NOT NULL /* 학급종료일 */
);

COMMENT ON TABLE CLASS IS '학급';

COMMENT ON COLUMN CLASS.CLASS_NO IS '학급번호';

COMMENT ON COLUMN CLASS.CLASS_START IS '학급시작일';

COMMENT ON COLUMN CLASS.CLASS_END IS '학급종료일';

CREATE UNIQUE INDEX PK_CLASS
	ON CLASS (
		CLASS_NO ASC
	);

ALTER TABLE CLASS
	ADD
		CONSTRAINT PK_CLASS
		PRIMARY KEY (
			CLASS_NO
		);

/* 회원 */
CREATE TABLE USERS (
	USER_ID VARCHAR2(200) NOT NULL, /* 이메일아이디 */
	CLASS_NO NUMBER, /* 학급번호 */
	USER_NICKNAME VARCHAR2(100) NOT NULL, /* 닉네임 */
	USER_PASSWORD VARCHAR2(100) NOT NULL, /* 비밀번호 */
	USER_NAME VARCHAR2(100), /* 이름 */
	USER_TEL VARCHAR2(100), /* 전화번호 */
	USER_BIRTH DATE, /* 생일 */
	USER_RATING NUMBER, /* 등급 */
	USER_THEME NUMBER, /* 테마 */
	USER_SIGN_DATE DATE NOT NULL, /* 가입일자 */
	USER_PIC BLOB /* 회원사진 */
);

COMMENT ON TABLE USERS IS '회원';

COMMENT ON COLUMN USERS.USER_ID IS '이메일아이디';

COMMENT ON COLUMN USERS.CLASS_NO IS '학급번호';

COMMENT ON COLUMN USERS.USER_NICKNAME IS '닉네임';

COMMENT ON COLUMN USERS.USER_PASSWORD IS '비밀번호';

COMMENT ON COLUMN USERS.USER_NAME IS '이름';

COMMENT ON COLUMN USERS.USER_TEL IS '전화번호';

COMMENT ON COLUMN USERS.USER_BIRTH IS '생일';

COMMENT ON COLUMN USERS.USER_RATING IS '등급';

COMMENT ON COLUMN USERS.USER_THEME IS '테마';

COMMENT ON COLUMN USERS.USER_SIGN_DATE IS '가입일자';

COMMENT ON COLUMN USERS.USER_PIC IS '회원사진';

CREATE UNIQUE INDEX PK_USERS
	ON USERS (
		USER_ID ASC
	);

ALTER TABLE USERS
	ADD
		CONSTRAINT PK_USERS
		PRIMARY KEY (
			USER_ID
		);

ALTER TABLE USERS
	ADD
		CONSTRAINT FK_CLASS_TO_USERS
		FOREIGN KEY (
			CLASS_NO
		)
		REFERENCES CLASS (
			CLASS_NO
		);
